server:
  port: 9310
spring:
  application:
    name: kraft-contract-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    password: ''
    port: 16379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 3000
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.windsoft.kraft.contract.server.user : debug