server:
  port: 9310
spring:
  application:
    name: kraft-contract-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
  main:
    allow-bean-definition-overriding: true

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.windsoft.kraft.contract.server.user : debug