server:
  port: 9200

spring:
  application:
    # 应用名称
    name: kraft-contract-gateway
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: USER-SERVER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://kraft-contract-user-server
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Path=/api/user/**
          filters:
            # 1：去除一个路径，2：去除2路径，以此类推
            - StripPrefix=1
        - id: MENU-SERVER
          uri: lb://kraft-contract-menu-server
          predicates:
            - Path=/api/menu/**
          filters:
            - StripPrefix=1
        - id: RESOURCE-SERVER
          uri: http://localhost:18080
          predicates:
            - Path=/api/resource/**
          filters:
            - StripPrefix=2
        - id: FILE-SERVER
          uri: lb://kraft-contract-file-server
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1
        - id: PROJECT-SERVER
          uri: lb://kraft-contract-project-server
          predicates:
            - Path=/api/project/**
          filters:
            - StripPrefix=1
        - id: PROJECT-SERVER
          uri: lb://kraft-contract-project-user-consumer
          predicates:
            - Path=/api/pu/**
          filters:
            - StripPrefix=1
        - id: AUTH-SERVER
          uri: lb://kraft-contract-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

# 目前无效
feign:
  sentinel:
    enabled: true

# 目前无效
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug