server:
  port: 9300
spring:
  application:
    name: kraft-contract-project-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 115.29.205.50:8848
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.29.205.50:3306/kraft-contract?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

feign:
  sentinel:
    enabled: true

mybatis:
  type-aliases-package: com.windsoft.kraft.contract.mybatis.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.windsoft.kraft.contract.server.user : debug