server:
  port: 9420
spring:
  application:
    name: kraft-contract-file-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848

upload:
  host: http://192.168.2.199:18080
  res:
    avatar: img/avatar